name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_IMAGE: ${{ helloworld-app }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t helloworld
          docker tag helloworld 244530008913.dkr.ecr.eu-west-1.amazonaws.com/diy-ecr
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/diy-ecr

      - name: Build and push to Docker hub
        run: |
          docker build . --tag DOCKER_IMAGE
          docker login --username tobiasliu1 --password DOCKER__PASSWORD
          docker tag DOCKER_IMAGE tobiasliu1/DOCKER_IMAGE
          docker push tobiasliu1/DOCKER_IMAGE
          
